-- MySQL Script generated by MySQL Workbench
-- Sat Mar  3 00:38:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Molino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Molino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Molino` DEFAULT CHARACTER SET utf8 ;
USE `Molino` ;

-- -----------------------------------------------------
-- Table `Molino`.`Condicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Molino`.`Condicion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `unidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molino`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Molino`.`Persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuitCuil` VARCHAR(12) NOT NULL,
  `razonSocial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molino`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Molino`.`Proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ingresosBrutos` INT NOT NULL,
  `inicioActividades` DATE NOT NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  INDEX `fk_Proveedor_Persona1_idx` (`Persona_id` ASC),
  CONSTRAINT `fk_Proveedor_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `Molino`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molino`.`Grano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Molino`.`Grano` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molino`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Molino`.`Contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `cerrado` TINYINT NOT NULL,
  `fechaLabra` DATE NOT NULL,
  `fechaLimite` DATE NOT NULL,
  `numero` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  `tipoContrato` VARCHAR(45) NOT NULL,
  `Proveedor_id` INT NOT NULL,
  `Grano_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Proveedor_id`, `Grano_id`),
  INDEX `fk_Contrato_Proveedor1_idx` (`Proveedor_id` ASC),
  INDEX `fk_Contrato_Grano1_idx` (`Grano_id` ASC),
  CONSTRAINT `fk_Contrato_Proveedor1`
    FOREIGN KEY (`Proveedor_id`)
    REFERENCES `Molino`.`Proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Grano1`
    FOREIGN KEY (`Grano_id`)
    REFERENCES `Molino`.`Grano` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Molino`.`ContratoDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Molino`.`ContratoDetalle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `Condicion_id` INT NOT NULL,
  `Contrato_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Condicion_id`, `Contrato_id`),
  INDEX `fk_ContratoDetalle_Condicion_idx` (`Condicion_id` ASC),
  INDEX `fk_ContratoDetalle_Contrato1_idx` (`Contrato_id` ASC),
  CONSTRAINT `fk_ContratoDetalle_Condicion`
    FOREIGN KEY (`Condicion_id`)
    REFERENCES `Molino`.`Condicion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ContratoDetalle_Contrato1`
    FOREIGN KEY (`Contrato_id`)
    REFERENCES `Molino`.`Contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
